---
- name: Create k8s Guestbook App
  hosts: all
  tasks: 
  - name: Create a k8s namespace
    k8s:
      name: "{{ k8s_namespace }}"
      api_version: v1
      kind: Namespace
      state: present
      
  - name: Deploy Kubedoom app
    k8s:
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            app: kubedoom
          name: kubedoom
          namespace: "{{ k8s_namespace }}"
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: kubedoom
          template:
            metadata:
              labels:
                app: kubedoom
            spec:
              hostNetwork: false
              serviceAccountName: kubedoom
              containers:
                - image: ghcr.io/storax/kubedoom:latest
                  env:
                    - name: "{{ k8s_namespace }}"
                      value: default
                  name: kubedoom
                  ports:
                    - containerPort: 5900
                      name: vnc
                
  - name: Create kubedoom service account
    k8s:
      definition:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: kubedoom
          namespace: "{{ k8s_namespace }}"

  - name: Create kubedoom ClusterRoleBinding
    k8s:
      definition:  
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: kubedoom
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
          - kind: ServiceAccount
            name: kubedoom
            namespace: "{{ k8s_namespace }}"

  - name: Create kubedoom service
    k8s:
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          labels:
            app: kubedoom
          name: kubedoom
          namespace: "{{ k8s_namespace }}"
          spec:
             type: LoadBalancer
             ports:
             - port: 5900
               #nodePort: "{{ k8s_nodeport }}"
               protocol: TCP
               targetport: vnc
             selector:
               app: kubedoom
               name: kubedoom

  - name: Create kubedoom Ingress Route
    k8s:
      definition:
        apiVersion: traefik.containo.us/v1alpha1
        kind: IngressRoute
        metadata:
        name: novnc
        spec:
        entryPoints:
            - websecure
        routes:
            - match: Host(192.168.1.79)
              kind: Rule
              services:
                  - name: vnc
                    port: 5900
        tls:
            certResolver: le
